### ISSUE TITLE
Executing as an authenticated user?

### ISSUE THREAD

**Issue by roja** [lengzuo/supa#8]
I may be missing something here but if I do something like:

```
 ctx := context.Background()
    
	    body := dto.SignInRequest{
		    Email:    "xxx@yyy.yyy",
		    Password: "zzzz",
	    }
    
	    resp, err := supaClient.Auth.SignInWithPassword(ctx, body)
```

and then attempt to use that supaClient again there is no token passed along with the request. There doesn't seem to be any other methods on the execute to pass the token in.

How do I execute queries in the context of an auth'd user? Or is this an unsupported requirement in the library?

**Comment by lengzuo** [comment]
Hi @roja thanks for the question and sorry for the late reply. 
I guess you have enabled the permission to only allow authenticated user to access the database query ? 
If my guess is correct, i think you have raised a really good question. 

Let me fix it ASAP. Thanks again for your time to open the issues.

**Comment by lengzuo** [comment]
Hi @roja, i just merged a PR that will potentially fix your issues.
Sample code as below:
```
ctx := context.Background()
body := dto.SignInRequest{
	Email:    "xxx@yyy.yyy",
	Password: "zzzz",
}
resp, err := supaClient.Auth.SignInWithPassword(ctx, body)
token := resp.AccessToken
var u []UserSubscription
query := supaClient.DB.From("user_subscriptions", postgres.AuthToken(token)).Select("*").Eq("user_id", "Your_User_ID")
err = query.Execute(ctx, &u)
```

I've added variadic parameters to the **.From** function. Now, after retrieving the user token, you can pass it to your subsequence database query using the **.From** function. 

Please close this issue if it has been resolved.

Thank you, **happy coding**.

**Comment by roja** [comment]
Thanks for this!
